// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxVlYIjOVsqNuV-QFYSUXWmL19MWBASck',
    appId: '1:306745383039:web:330e3db0841e6a0865c74a',
    messagingSenderId: '306745383039',
    projectId: 'chatbot-54001',
    authDomain: 'chatbot-54001.firebaseapp.com',
    storageBucket: 'chatbot-54001.appspot.com',
    measurementId: 'G-8KNSQ8H6FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZizDkgdrQTZmkSckznrtRGiPEgzrZi4g',
    appId: '1:306745383039:android:8b534bfd34e3a0df65c74a',
    messagingSenderId: '306745383039',
    projectId: 'chatbot-54001',
    storageBucket: 'chatbot-54001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL0DBG0H-ieYQAzgGbNa96FNIOxwm6I4g',
    appId: '1:306745383039:ios:a158bcb01a0ec7d365c74a',
    messagingSenderId: '306745383039',
    projectId: 'chatbot-54001',
    storageBucket: 'chatbot-54001.appspot.com',
    iosBundleId: 'com.nyxeldevid.tanyaWii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL0DBG0H-ieYQAzgGbNa96FNIOxwm6I4g',
    appId: '1:306745383039:ios:a158bcb01a0ec7d365c74a',
    messagingSenderId: '306745383039',
    projectId: 'chatbot-54001',
    storageBucket: 'chatbot-54001.appspot.com',
    iosBundleId: 'com.nyxeldevid.tanyaWii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxVlYIjOVsqNuV-QFYSUXWmL19MWBASck',
    appId: '1:306745383039:web:b505c959450a49a065c74a',
    messagingSenderId: '306745383039',
    projectId: 'chatbot-54001',
    authDomain: 'chatbot-54001.firebaseapp.com',
    storageBucket: 'chatbot-54001.appspot.com',
    measurementId: 'G-SCFW8C0X3J',
  );
}
